name: Github Actions

on:
  push:
    branches:
      - main

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello World Print
        run: echo "Hello World"

      - name: Build
        run: npm run build
